version: '3.8'

services:
  dedenbangkit:
    image: node:latest
    container_name: dedenbangkit-dev
    working_dir: /app
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    command: sh -c "npm install && npm start"
    stdin_open: true
    tty: true
